#!/usr/bin/env bash
set -e
command=$1
VPM_LIBEXECDIR=${VPM_LIBEXECDIR:-""}

if [[ -z "$VPM_LIBEXECDIR" ]]; then
cat <<-LIBEXEC_NOTICE
vpm: VPM_LIBEXECDIR is not set!

    You can either export it

      ~ \$ export VPM_LIBEXECDIR=/path/to/vpm/libexec
      ~ \$ vpm

    or set it during execution.

      ~ \$ VPM_LIBEXECDIR=/path/to/vpm/libexec vpm
LIBEXEC_NOTICE
exit 1
fi

export PATH="$VPM_LIBEXECDIR:$PATH"

if [[ ! -f "$HOME/.vim/autoload/pathogen.vim" ]]; then
  vpm-pathogen-instructions
  exit 1
fi

case "$command" in
  ""|"-h"|"--help")
    vpm-help
    ;;
  "-v"|"--version")
    vpm-version
    ;;
  *)
    if command -v "vpm-$command" > /dev/null; then
      shift && exec "vpm-$command" "$@"
    else
      vpm-insert "$@"
    fi
    ;;
esac
