#!/usr/bin/env bash
set -e
plugin_name=$1

cd $(vpm-plugin-directory)

if [ -z $plugin_name ]; then
  echo "vpm: missing argument PLUGIN"
  exit 1
fi

if [ -d $plugin_name ]; then
  rm -rf $plugin_name
  echo "vpm: \`$plugin_name' removed"
  exit 0
else
  echo "vpm: \`$plugin_name' not inserted"
  exit 1
fi
