#!/usr/bin/env bash
set -e
plugin=$1
plugin_name=$(basename "$plugin")
plugin_repository="git@github.com:$plugin.git"

cd $(vpm-plugin-directory)

if [ -z $plugin_name ]; then
  echo "vpm: missing argument PLUGIN"
  exit 1
fi

if [ -d $plugin_name ]; then
  echo "vpm: \`$plugin_name' already inserted"
  exit 1
fi

if git clone $plugin_repository; then
  echo "vpm: \`$plugin_name' inserted"
  exit 0
else
  echo "vpm: \`$plugin_name' could not be inserted"
  exit 1
fi
