#!/usr/bin/env bash
set -e

cd $(vpm-plugin-directory)

if [[ ! -f "$(vpm-plugin-file)" ]]; then
  echo "vpm: \`$(vpm-plugin-file)' is not present"
  exit 1
fi

while read plugin; do
  plugin_name=${plugin##*/}
  plugin_repository="git@github.com:$plugin.git"

  if [[ -d "$plugin_name" ]]; then
    echo "vpm: using \`$plugin_name'"
    continue
  fi

  if git clone $plugin_repository; then
    echo "vpm: \`$plugin_name' inserted"
  else
    echo "vpm: \`$plugin_name' could not be inserted"
  fi
done < $(vpm-plugin-file)
